[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run db:push && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 